### ISSUE TITLE
JPA Auditing

### ISSUE THREAD

**Issue by paullee714** [photopieproject/BE_Finally#63]
https://github.com/photopieproject/BE_Finally/blob/bbdb80920df900a08f43402867b3acadab988c07/src/main/java/com/sparta/be_finally/config/model/Timestamped.java#L16

Auditing 사용하신 부분 너무 좋습니다~! 이렇게 createdAt, updatedAt 관리하시면 중복되지않고 동일하게 관리할수있어서 좋아요~!
다만 패키지 위치가 애매해요~
config와 동일한 레벨에서 common을 만들어 관리하시면 좋을 것 같네요~ !

**Comment by OhYeonJu** [comment]
Common 패키지 만들어서 수정했습니다!
